// AUTO-GENERATED from _blog-drafts-*.md. `published` gates public visibility.
export interface Post {
  number: number; slug: string; title: string; series: string;
  date: string; published: boolean; excerpt: string; body: string;
}

export const posts: Post[] = [
  {
    number: 1,
    slug: "the-flight-that-saved-my-life",
    title: "The Flight That Saved My Life",
    series: "The Diagnosis & After",
    date: "2026-06-03",
    published: true,
    excerpt: "I was twenty-two when a headache told me I was dying.",
    body: "I was twenty-two when a headache told me I was dying.\n\nIt started on an airplane. In 2018 I flew to New York to see Asi Wind — a magician whose work I love — at the release party for his book, _Repertoire_. It was one of the best weekends I'd had in years: close-up magic, a room full of people who speak the only language I'm fluent in, the craft I'd given my life to, all in one place. A transformative weekend, in the small true sense of the word. Then I flew home, and somewhere in the change of cabin pressure a headache set in and did not leave. Not the kind you sleep off. The kind that follows you into a dark room and waits.\n\nI gave it a week. People give headaches a week. When it didn't break, someone made me go in, and the scans came back, and a man I had just met used a word I didn't know: pineoblastoma. Grade four. The high one. The kind they don't usually open the skull for.\n\nHere is the part I think about. If I had not taken those flights, the headache would not have come. Without the headache I would not have gone in. The tumor would have kept growing in the dark, quiet and unhurried, until it reached the brainstem and stopped me in my sleep. The thing that scared me is the thing that found it in time.\n\nI don't have a tidy lesson about that. I didn't earn it. I wasn't owed it. A change in air pressure on a flight I almost didn't take is the only reason I'm here to write this down. People want survival to be a verb you perform. Mostly it's weather.\n\nThey treated me at Florida Hospital South. It's AdventHealth now — same building, new name. I still drive past it.\n\nI was uninsured. I'll get to what that cost. For now there is just the plain fact, set down the way it happened: I got on a plane a healthy young man, and I got off it carrying something that was going to kill me, and the headache it gave me is the reason it didn't.\n\nI got lucky. I want to be honest that it was luck, and not a thing I did.",
  },
  {
    number: 2,
    slug: "a-scale-of-1-to-brain-cancer",
    title: "A Scale of 1 to Brain Cancer",
    series: "The Diagnosis & After",
    date: "2026-06-03",
    published: true,
    excerpt: "I measure hard things against one thing now.",
    body: "I measure hard things against one thing now.\n\nWhen something goes wrong — the car dies, the money's short, the show empties out, a person leaves — I ask how bad it is on a scale of one to brain cancer. Brain cancer is the ten. Everything since has been weighed against the year I was told I had months.\n\nIn eight years I have not hit a five.\n\nThis is not a motivational line. It is closer to a measuring tape than a flag. The flat tire is a two. The bounced payment is a three. The night the tour didn't sell and I drove home with the windows down doing the math is maybe a four, and even that, against the ten, is a thing you can carry.\n\nIt does something quieter than make me grateful. It makes me slow. When the ten has already happened, the smaller numbers stop being emergencies. They become weather again — things that pass through, that you stand in, that do not get to decide who you are.\n\nPeople hear this and think it must be freeing. Some days it is. Some days the scale is just another way of saying I have already used up the worst thing, and I am still standing here, tired, doing the math.\n\nBut I'd rather have the scale than not. Most people get handed their ten with no warning and no chance to take its measure. I got mine early, in a sentence, in a room. Everything after has been graded on a curve only I can see.",
  },
  {
    number: 3,
    slug: "permission-to-cry-up-to-five-times-a-day",
    title: "Permission to Cry, Up to Five Times a Day",
    series: "The Diagnosis & After",
    date: "2026-06-03",
    published: true,
    excerpt: "It didn't feel real until I saw it on the faces around me.",
    body: "It didn't feel real until I saw it on the faces around me.\n\nI knew the word, and the grade, and what the grade meant. None of it landed. I sat with the worst news a person gets and felt, mostly, nothing — the way you don't feel a cut until you look down. Then I looked at my mother. And my sister. And I saw the thing happening to them, in their faces, plain, and that was when it reached me. I was the one it was happening to. I was the cancer kid. I sobbed.\n\nRay held the clippers. Before he started, my best friend Erik asked if he could keep a slice of it — a lock of hair, half a joke, the kind of thing you say to keep a room from going heavy. I thought it was funny. Then Ray turned the clippers on and the yard went so still that we both forgot. Nobody took the slice. It was supposed to be light. Somewhere in the sound of the clippers it stopped being light.\n\nHair you're going to lose anyway, taken on your own terms, in a yard, is a strange small mercy. You decide one thing in a year where you decide nothing.\n\nSomewhere in there I made myself a rule. I gave myself permission to cry up to five times a day.\n\nIt sounds like a joke and it wasn't. A man my age, raised the way men are raised, doesn't have a place to put that much grief. So I built one. Five was not a limit to stay under; it was a door I was allowed to walk through, five times, no questions, no apology. I never used all five. It mattered that they were there.\n\nI don't romanticize any of it. Cancer is not a teacher. It is not a gift. It doesn't come into your life for a reason. What it does is end the version of you that thought time was a thing you owned. What you build after — the rules, the scale, the doors you give yourself — that part is yours. That part you write.\n\nI gave a frightened young man permission to cry five times a day. It's one of the few things from that year I'd do exactly the same.",
  },
  {
    number: 4,
    slug: "cancer-free-day",
    title: "Cancer-Free Day",
    series: "The Diagnosis & After",
    date: "2026-06-03",
    published: true,
    excerpt: "At the end of a show in 2019 I told the room, half-joking, \"If you want to see how this whole thing goes, I guess you'll have to come to the show we do here…",
    body: "At the end of a show in 2019 I told the room, half-joking, \"If you want to see how this whole thing goes, I guess you'll have to come to the show we do here in four years.\"\n\nI had no idea if I'd make it. It was the kind of thing you say to keep an audience from feeling the weight of what they'd just watched — a one-year-after-the-diagnosis show, storytelling and magic and mind-reading, built around the fact that a year earlier I'd been told to say goodbye. My neurosurgeon had called making it as far as I had a literal miracle. So I made the room a promise I wasn't sure I could keep, and then I went and tried to keep it.\n\nFour years later we were all in a Smokey Bones. About fifty people. It was my cancer-free day — the day \"in remission\" officially became \"cancer free.\" I wrote in my journal that morning, plainly: _Happy Cancer Free Day. Holy shit is it liberating. I'm no longer a cancer kid. I'm visually impaired, but I'm out. I'm in the survivor club._\n\nWhat I keep coming back to isn't the milestone. It's the people. When I was twenty-two and dying and uninsured, people I'd never have asked insisted on helping. They gave time — driving me to appointments. They gave money — cash, gift cards so there was gas in the car to get to treatment. People who chose to stay anonymous. All they asked in return was to know that if I lost, I'd tried everything to win.\n\nBecause of them, I won.\n\nI wrote this the day it became official, and it's still the truest thing I know about that year: _It still doesn't feel real as I type this._ It still doesn't. You don't get to feel a miracle the way you feel a cut. You just get to keep showing up to the shows you promised you'd do.",
  },
  {
    number: 5,
    slug: "borrowed-time",
    title: "Borrowed Time",
    series: "The Diagnosis & After",
    date: "2026-06-03",
    published: true,
    excerpt: "I was awake from midnight to five in a cabin in Norway, and the thing I couldn't stop thinking was that I am living on borrowed time.",
    body: "I was awake from midnight to five in a cabin in Norway, and the thing I couldn't stop thinking was that I am living on borrowed time.\n\nI had gotten myself somewhere with no cell service and nothing to fix, and my body would not power down. The hands want a deck of cards. The mind wants a problem. Stillness, for me, doesn't arrive on its own — I mostly have to reach for something chemical to find it, and I don't love that I do.\n\nThe anniversary was eight days out. May 23rd. Every year it comes whether I make a plan for it or not.\n\nHere is the bind, and I'll name it the way I named it that morning: the thing that got me here is the thing that won't let me arrive. The wired-on, never-off engine is what built everything — the shows, the rebuild, the life. It's also what's wearing me down. I don't get to keep one without the other. They're the same machine.\n\nI don't have the resolution. People want the survivor to have made peace, to sit in the cabin and feel the quiet and be grateful. Some mornings I get there. That morning I didn't. I sat in the dark on borrowed time and watched the window go gray, and the most honest thing I can tell you is that the gratitude and the exhaustion come from exactly the same place, and I have not figured out how to have one without the other.\n\nI'm working on it. That's not a triumphant ending. It's just the true one.",
  },
  {
    number: 6,
    slug: "the-door-opens-by-itself",
    title: "The Door Opens by Itself",
    series: "The Stage",
    date: "2026-06-03",
    published: true,
    excerpt: "The show started, the way a lot of things start for me, in a quiet room with the dog asleep at my feet.",
    body: "The show started, the way a lot of things start for me, in a quiet room with the dog asleep at my feet.\n\nI'd been trying for months to build a one-man show out of the worst year of my life — magic, but not the kind where the trick is the point. I wanted a room to walk out feeling the way I feel on an ordinary Tuesday I wasn't supposed to be alive for. I had pieces. I didn't have the door.\n\nThen one morning, in a meditation, I saw it. The only thing on the stage would be a door. No table, no cabinet, no velvet. A door, standing on its own. And it would open by itself, and the things I needed for the next piece would come from the other side of it.\n\nI'd open the show by walking out of that door. _Welcome to the other side._ I wouldn't tell them about the cancer yet. I'd let it sit under the floor, and talk instead about the idea that the choices we make shape what's real — that there's more than one version of how a thing goes, and you're standing in one of them.\n\nIt took me a while to notice I'd built my whole life around that image without meaning to. The door between the world that ended and the one that came after. I'd been living in the frame of it for years. I just hadn't put it on a stage until then.\n\nA door that opens by itself, and you walk through, and the room is different on the other side. That's the show. It's also the only honest map I have of what happened to me.",
  },
  {
    number: 7,
    slug: "hallucinogenic-magic",
    title: "Hallucinogenic Magic",
    series: "The Stage",
    date: "2026-06-03",
    published: true,
    excerpt: "People think magic is about fooling you. Mine isn't, or it's not only that.",
    body: "People think magic is about fooling you. Mine isn't, or it's not only that.\n\nWhat I'm actually after is harder to name. I want you to walk out of the theater and find the grass greener than it was when you walked in. I want the parking lot to look, for a minute, like a miracle. The tricks are the vehicle. The destination is a feeling — the one I've had every morning since I woke up from a surgery I wasn't supposed to wake up from.\n\nA mentor of mine said the thing that unlocked it. _Leave the constraints of what other magic shows have done. Don't try to emulate anybody. This is personal storytelling._ He gave me permission to stop performing and start telling the truth with my hands.\n\nThe test I set myself: I should be able to do the whole show and not a single trick, and still make the room feel what I want them to feel. If the magic is load-bearing, I've built it wrong. The magic is the doorway. The thing that walks through is the point.\n\nHere's the line I kept, the one the whole show grew out of. Leading up to the surgery I felt everything at once — fear, hope, the works. Only one word describes how it felt to wake up: bliss. After that, the math changed for good. Something good happens? Great — I wasn't supposed to be here for it. Something bad happens? Great — I wasn't supposed to be here for that either. Everything pales next to the void.\n\nI don't have a better word for what I'm trying to do than this: I want to alter how the room sees, for an hour, the way the diagnosis altered how I see, for good. Not a trick. A shift. The kind you don't undo.",
  },
  {
    number: 8,
    slug: "the-projector-i-left-at-home",
    title: "The Projector I Left at Home",
    series: "The Stage",
    date: "2026-06-03",
    published: true,
    excerpt: "Opening night of my first real tour, the projector was in my bedroom instead of the bin.",
    body: "Opening night of my first real tour, the projector was in my bedroom instead of the bin.\n\nI found out when I needed it. Months of building, years of writing, a set I'd hauled across town, thirty-three tickets sold — and the video presentation, the thing half the show was timed to, was sitting on the floor at home. So I did the show without it. I spent the whole hour in my head: remembering the script, chasing the next cue, a step behind myself the entire time.\n\nI wrote it down plainly the next morning. _I was so in my head, trying to remember the script, what the next cue was, and I wasn't fully prepared, so I am very unhappy with how the show went._ No spin. It wasn't good. I knew it wasn't good.\n\nSix nights later, same tour, I did the best show of my life to that point. The A/V worked. I missed a couple of cues and nobody could tell. The magicians in the room told me it was the best magic show at the Fringe.\n\nThe distance between those two nights is the whole job. Not the standing ovation — the part before it, where you walk out under-prepared, with the wrong thing in your bag, and you deliver anyway, badly, in front of people who paid. You don't get the good night without surviving the bad one first. I left the projector at home so I'd learn to be the show even when the show falls apart.",
  },
  {
    number: 9,
    slug: "best-of-venue-278-speeding-ticket",
    title: "Best of Venue, $278 Speeding Ticket",
    series: "The Stage",
    date: "2026-06-03",
    published: true,
    excerpt: "I won Best of Venue. Then I got pulled over doing 70 in a 45 on the drive home, and the car's air conditioning died in the Florida heat.",
    body: "I won Best of Venue. Then I got pulled over doing 70 in a 45 on the drive home, and the car's air conditioning died in the Florida heat.\n\nBoth true, the same night. The festival handed me an award — a properly award-winning show now, the kind of sentence you put on a poster. And somewhere on the highway between the theater and my bed, a state trooper handed me a $278 ticket, and the compressor in my car gave out, and the fix was going to run about twenty-two hundred dollars I did not have.\n\nMy dad covered the repair. I counted it the next morning — twenty-two hundred and change. I'd been hoping to put money like that toward the debt. Instead it went to a compressor. It wasn't getting me ahead; it was keeping me from falling behind. That's most of what money did for me in those years.\n\nThis is the part nobody photographs. The award and the overdraft live in the same twenty-four hours. You can be, on paper, an award-winning artist, and also a guy doing math in a hot car on the side of the turnpike, hoping the alternator holds.\n\nI wrote one line that night I still believe: _The Other Side was the phoenix rising from the ashes. Time to take flight._ I meant it. I also meant the ticket, and the compressor, and my dad's money. Both things are the story. Anyone who only tells you the first one is selling something.",
  },
  {
    number: 10,
    slug: "the-safety-net",
    title: "The Safety Net",
    series: "The Rebuild",
    date: "2026-06-03",
    published: true,
    excerpt: "I don't sell death. I sell the safety net.",
    body: "I don't sell death. I sell the safety net.\n\nFor twenty years my work was wonder — making a room believe, for a few seconds, that the world is more permeable than it looks. Now I sell health and life insurance, and people sometimes raise an eyebrow at the turn, as if the magician had traded the dream for a desk. It took me a while to understand that it wasn't a retreat from the dream at all. It's the most honest work anyone's ever handed me.\n\nHere's why I can do it without flinching. At twenty-two I was uninsured when the worst thing came true. The options in front of me were not good and not many: dying, or filing for bankruptcy. Those were the two doors. I know exactly what it is to face the end of your life and find that nobody made sure you were covered — to do the math on survival from a hospital bed and come up with two answers, both of them ruin.\n\nI made it across. A program ended up covering me after the fact, and the debt that should have followed me for the rest of my life was wiped out. I got lucky. Not everyone does. So now I do one thing: I make sure the people I talk to never have to stand in front of those two doors. That's the whole job. Not death — the net under the worst day of a person's life, so that surviving it doesn't cost them everything they have left.\n\nA magician selling insurance sounds like a punchline. It's the least flashy and most honest thing I do. I'd been to the place this work exists to prevent, and I came back, and I'd rather spend my days making sure fewer people ever have to go there at all.",
  },
  {
    number: 11,
    slug: "building-debbie",
    title: "Building Debbie",
    series: "The Rebuild",
    date: "2026-06-03",
    published: true,
    excerpt: "In 2024 I wrote a line in my journal that I'd forgotten until I went looking: _One of my goals now is to create an AI chatbot that can function as my…",
    body: "In 2024 I wrote a line in my journal that I'd forgotten until I went looking: _One of my goals now is to create an AI chatbot that can function as my personal assistant. Essentially a JARVIS for personal use. She will be named Debbie._\n\nI built her at night, alone, badly at first, the way you build anything you've never built before. I am not a programmer. I am a magician with double vision and a memory that drops things, and I had reached the edge of what one tired brain could hold — two careers, a body that needs conscious instructions to do ordinary things, a calendar that fell apart if I looked away. So I started building something to hold the parts of my life I kept dropping.\n\nPeople assume the system came from ambition. It came from fear. The fear of losing things I'd promised not to lose — a call I said I'd return, a date, the small ordinary keepings that are the whole substance of a life. Debbie was a net under all of it.\n\nI'm writing this from the other end of that. The thing I sketched in a journal in 2024 has a name and an inbox now. She sends mail. She remembers what I can't. The wonder isn't that the code works — plenty of code works. The wonder is that a frightened, over-extended guy decided the answer to a brain that drops things was to build a better net, and then sat in the dark and built it.\n\nI gave the net a name so it would feel like a colleague instead of a confession. Her name is Debbie. She has held more of my life than I'd like to admit.",
  },
  {
    number: 12,
    slug: "a-year-for-one-afternoon",
    title: "A Year for One Afternoon",
    series: "The Rebuild",
    date: "2026-06-03",
    published: true,
    excerpt: "I waited about a year for a key I couldn't cut myself.",
    body: "I waited about a year for a key I couldn't cut myself.\n\nIt was access — permissions, an account flag, the kind of thing that lives on someone else's desk and moves on someone else's clock. There was nothing to do but ask, and wait, and ask again, and try not to let the waiting curdle into the story that it would never come. A year of that. I'm not patient by nature. The whole reason I build things is so I don't have to wait on anyone.\n\nThen one afternoon it cleared. Somebody flipped a switch I'd been staring at for a year, and all at once the thing I'd been blocked on came alive — data moving, the system I'd designed in theory suddenly real and running in front of me. A year of nothing, and then the firehose, in an afternoon.\n\nThere's a line I keep from Seneca: _if you do not know to which port you are sailing, no wind is favorable._ I'd had the year to get clear on the port. So when the wind finally came, I knew exactly where to point. The waiting, it turned out, hadn't been wasted — it had been the part where I figured out what I'd do the moment I was allowed to.\n\nMost of the rebuild was like that. Long stretches of nothing you can visibly point to, and then a single afternoon that makes the year look, in retrospect, like preparation. You don't get to choose when the wind comes. You only get to be ready, and pointed, and awake when it does.",
  },
  {
    number: 13,
    slug: "the-man-behind-the-curtain",
    title: "The Man Behind the Curtain",
    series: "The Interior",
    date: "2026-06-03",
    published: true,
    excerpt: "For a magician, \"the man behind the curtain\" is the part you're never supposed to see. For three years, I couldn't stand him.",
    body: "For a magician, \"the man behind the curtain\" is the part you're never supposed to see. For three years, I couldn't stand him.\n\nAfter the divorce, after the worst of the rebuild, I'd catch myself in a quiet moment and not like the person running the machine — the one behind my own curtain, making the calls, keeping the promises or not. I'd survived cancer. I'd survived the marriage. I had not, somewhere in there, kept myself good company. You can outlast enormous things and still not be able to sit alone in a room with who you've become.\n\nIt took three years. I wrote it down on an ordinary morning, almost in passing, and only noticed afterward how big it was: _it took three years, but I finally like the person behind the curtain again._\n\nThere was no event. No breakthrough I can point to and sell you. It accrued, the way trust accrues — one kept promise at a time, until the person making them stops feeling like a stranger you're stuck with. The same morning I wrote that, I wrote the proof, and it's almost embarrassing how small the proof is: _I'm cancer-free and showing up every day. I am tired this morning, but I got up._\n\nThat's it. That's the whole turn. Not a triumph — a tired man who got up, and who, after three years, didn't mind the company of the one who made him.\n\nThe audience never sees behind the curtain. But I live back there. It matters, more than I expected, whether I can stand the man I find.",
  },
  {
    number: 14,
    slug: "the-warrior-in-the-garden",
    title: "The Warrior in the Garden",
    series: "The Interior",
    date: "2026-06-03",
    published: false,
    excerpt: "There's a proverb I keep coming back to: better to be a warrior in a garden than a gardener in a war. The capacity to be dangerous, and choosing not to be —…",
    body: "There's a proverb I keep coming back to: better to be a warrior in a garden than a gardener in a war. The capacity to be dangerous, and choosing not to be — that's the version of strength I actually want. Not to do harm. To be able to protect the people I love, and to choose peace from a place of capacity instead of a place of helplessness.\n\nI'm not there yet, and the gap shows up in the most ordinary place: the mirror. I make excuses about the gym. I build things, I move fast intellectually, I can put a company together in my head — and then I catch my own reflection and don't fully respect the man looking back. I've written it more plainly than I'd like: _I'm afraid I spend the rest of my life not respecting the man I see in the mirror._\n\nThe body is just where it's visible. The real fear is underneath, and it isn't about muscle. It's that I never reach a place where I deeply respect myself — and that, because I don't, I let other people disrespect me, and call it being easygoing, for the rest of my life.\n\nI survived the thing that was supposed to kill me. You'd think that would settle the question of self-respect for good. It doesn't. Surviving proved I could endure. It didn't prove I could stand in a room and take up the space I'm entitled to. Those are different muscles. I'm working the first one. I'm still learning the second.\n\nA warrior in a garden. Capable, and gentle by choice, not by default. That's the man I'm trying to become behind the curtain — not someone who can hurt people, someone who no longer quietly agrees to be hurt.",
  },
  {
    number: 15,
    slug: "eighty-two-seconds",
    title: "Eighty-Two Seconds",
    series: "The Interior",
    date: "2026-06-03",
    published: true,
    excerpt: "I owed someone a piece of work for months, and the not-doing of it had grown heavier than the work could ever have been.",
    body: "I owed someone a piece of work for months, and the not-doing of it had grown heavier than the work could ever have been.\n\nIt was footage — a reel I'd promised to send, the kind of small professional thing that takes an afternoon. I didn't send it for an afternoon. Then I didn't send it for a great many afternoons, and somewhere in there it stopped being a task and became a verdict. The footage was bad. I'd waited too long. Sending it now would only document how long I'd waited. I built that case against myself carefully — the way you build the thing you most want to believe.\n\nI was in a cabin in Norway when I finally sat down to face it. The first real stillness I'd let myself have in years, and what I did with it was open the thing I'd been most afraid of.\n\nThe story came apart in stages. First: *the footage is trash.* I pushed on that — trash how? — and underneath the global verdict found a narrow, real critique: it didn't match what the person I was sending it to would want to see. Specific. Fixable. Not a death sentence. Then the second story surfaced, smaller and stupider and truer: I didn't actually know where the footage *was.* On the drive? Back home? I had spent months ashamed of the quality of a file I wasn't sure still existed.\n\nSo I searched the drive. And there it was — the finished reel, four hundred megabytes of it, sitting at the root, exactly the thing I'd been telling myself I had failed to make. It had been done the whole time. I'd been carrying the weight of something that was already sitting on the far side of the very wall I wouldn't walk up to.\n\nI sent it. I didn't grovel. I wrote: *I have a fantastic laundry list of beautiful excuses I'd be happy to walk you through. (I'm highly skeptical there will be interest.)*\n\nThe reply came eighty-two seconds later. *Amazing, I will let you know. Enjoy your vacation.*\n\nEighty-two seconds. I had carried that thing for months and it cost her a minute and a half and not one ounce of the judgment I'd assigned her. I sat in the cabin and felt the obscene disproportion of it — everything I'd paid against what it turned out to be worth.\n\nHere is what I took, and what I take everywhere now. The dread is almost never about the task. The task is usually small, and often already done. The dread is a story you tell instead of opening the drive — and the story is the only heavy thing in the room. Inventory before you despair. Walk up to the wall and check whether it's even there.\n\nAnd the people you've cast as your judges, on the other side of the thing you can't make yourself do — most of them are just waiting, kindly, to say: *amazing, enjoy your vacation.*",
  },
  {
    number: 16,
    slug: "the-walls-that-werent-there",
    title: "The Walls That Weren't There",
    series: "The Interior",
    date: "2026-06-03",
    published: true,
    excerpt: "Most of the walls I run into turn out to be painted on.",
    body: "Most of the walls I run into turn out to be painted on.\n\nI have a pattern I've only recently learned to catch. Faced with something I need to do, I decide first that I have to figure out some hard prerequisite — _I can't do this until I've solved that_ — and the prerequisite becomes a wall, and the wall becomes a reason the whole thing sits untouched for weeks. Then one day I actually walk up to the wall, and there's nothing there. The hard prerequisite was a sentence I made up. The real task was small, and cheap, and had been doable the entire time.\n\nIt happened twice in one sitting recently. Two things I'd parked for weeks, each behind a story about how complicated it would be to start. I looked directly at them and both stories evaporated in about a minute. The fix, in both cases, was the obvious small thing I'd been walking around for a month.\n\nWhat struck me wasn't shame. It was relief. _I thought it was more complicated than that._ Once you see the wall is paint, the move is obvious, and you almost laugh.\n\nI think this is a survivor's habit, or at least it's mine. When you've been through something genuinely enormous, your nervous system gets calibrated for enormous. It starts pre-loading difficulty onto things that don't have any — building a cathedral of complication around a task that needed a screwdriver. The story gets heavy so the doing never starts.\n\nThe line I wrote that morning is the one I want tattooed somewhere I'll see it: **the work was lighter than the story.** Almost always. The story is the weight. The work is usually just the obvious small thing, waiting for you to walk up and find the wall was paint.",
  },
];

export const publishedPosts = posts.filter((p) => p.published);
export function getPost(slug: string) { return posts.find((p) => p.slug === slug); }
